class UserSerializer < ActiveModel::Serializer
  attributes :id, 
  :email,
  :password,
  :first_name, 
  :last_name,
  :profile_picture,
  :city,
  :tags,
  :pronouns,
  :interested_in,
  :birthday,
  :join_date,
  :linked_url,
  :instagram_url,
  :twitter_url,
  :other_url,
  :join_date,
  :created_at,
  :updated_at
end
